name: Opam
on:
  push:
    branches: [main]
  pull_request:

# This will cancel previous runs when a branch or PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ocaml-compiler: [5.3.0]

    steps:
      - name: Setup node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: "22"
          check-latest: true

      - name: Checkout project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true

      - name: Setup OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@a469f024d895044624e9f50ade2f9517d4d6a1ed # v3.4.8
        if: ${{ !startsWith(matrix.os, 'windows-') }}
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      # Try workaround to get msvc
      - name: Setup OCaml ${{ matrix.ocaml-compiler }}
        uses: anmonteiro/setup-ocaml@31973cef604a70a2b25e9a6f42bc2a04f24aa051 # v3.4.8 + cygwin mirror
        if: ${{ startsWith(matrix.os, 'windows-') }}
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}

      - name: Inspect depexts
        run: |
          # Check build systems 
          opam exec -- which cmake
          echo "Clang"
          opam exec -- which clang
          opam exec -- which clang++
          opam exec -- clang --version
          opam exec -- clang++ --version
          echo "GCC"
          opam exec -- which gcc
          opam exec -- which g++
          opam exec -- gcc --version
          opam exec -- g++ --version

      - name: Install local dependencies
        run: opam install . --deps-only --with-test

      - name: Build project
        run: opam exec -- dune build

      - name: Run tests
        run: opam exec -- dune runtest --display=short
